model:
  name: 'rgrnet'
  variant: 'lightweight'
  num_classes: 10
  input_channels: 3
  image_size: 224

training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  optimizer: 'adamw'
  scheduler: 'cosine'

data:
  dataset_path: './data/gestures'
  augmentation: true
  normalize: true